import math as m
print(m.sqrt(5))
print(m.ceil(4.5))
print(m.copysign(4,-4))
print(m.fabs(-5))
print(m.factorial(2))
print(m.floor(3.6))
print(m.fmod(2,3))
print(m.frexp(2))
print(m.e*2)
print(m.pi*2)
print(m.degrees(2))
print(m.radians(30))
print(m.hypot(4,3))
print(int(m.log10(14)))
print(m.trunc(532))
print(m.modf(5.5))
m.function()